# Generated by Django 5.2.7 on 2025-10-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('po', 'Purchase Order')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('extracted', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
